image: Visual Studio 2019

environment:
  matrix:
    - NAME: MSI
      SCRIPT: msi\build.msi.bat
      ARTIFACT: scripts\win32\packages\msi\wix\bin\apk-editor-studio_win32_dev.msi
    - NAME: ZIP
      SCRIPT: zip\build.zip.bat
      ARTIFACT: scripts\win32\packages\zip\apk-editor-studio_win32_dev.zip

install:
  - set QTDIR=C:\Qt\5.15.0\msvc2019
  - set OPENSSL=C:\OpenSSL-v111-Win32\bin
  - set WIXDIR=C:\Program Files (x86)\WiX Toolset v3.11\bin
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x86
  - C:\Python37\python scripts\download.py

before_build:
  - cd scripts\win32\packages

build_script:
  - call %SCRIPT%

artifacts:
  - path: $(ARTIFACT)
    name: $(NAME)

deploy:
  - provider: GitHub
    tag: development
    release: Developer Build
    draft: false
    prerelease: true
    force_update: true
    auth_token:
      secure: F4j34oc5G2EocYZKQVCbPpEM3wH9h20rCsQ8WhSHZ5dlg2SqtRDmQi13+CScmhYn
