language: cpp

before_script:
  - python3 scripts/download.py

matrix:
  include:
  - name: Linux (DEB)
    os: linux
    compiler: gcc
    install:
      - sudo apt-get install qt5-default qttools5-dev-tools libsecret-1-dev debhelper devscripts fakeroot
    script:
      - cd scripts/linux/packages/deb
      - ./build.deb.sh
      - mv apk-editor-studio_linux_{*,dev}.deb
      - cd -

  - name: Linux (AppImage)
    os: linux
    compiler: gcc
    before_install:
      - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-xenial -y
      - sudo apt-get update -qq
    install:
      - sudo apt-get install qt510base qt510imageformats qt510svg qt510tools libgl1-mesa-dev libsecret-1-dev adb zipalign
      - source /opt/qt510/bin/qt510-env.sh
    script:
      - cd scripts/linux/packages/appimage
      - ./build.appimage.sh
      - mv apk-editor-studio_linux_{*,dev}.AppImage
      - cd -

  - name: macOS
    os: osx
    compiler: clang
    install:
      - brew uninstall --ignore-dependencies qt
      - brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/a3e89f6b3fcfd6f4240360053b0f730e8ce4a74d/Formula/qt.rb
      - brew link qt --force
      - nvm install node
      - npm i appdmg
    script:
      - cd scripts/macos/packages
      - app/build.app.command
      - dmg/build.dmg.command
      - mv app/apk-editor-studio_macos_{*,dev}.app.zip
      - mv dmg/apk-editor-studio_macos_{*,dev}.dmg
      - cd -

before_deploy:
  - export TRAVIS_TAG=development

deploy:
  provider: releases
  api_key:
    secure: "WtUyLKiBPfQsGQo5Mg/SfdyPoUhsrx0bMMNOw21PO2I8GYeMrwq/SiWjS9kDdUaQ1rZ2EHq25nAiX5Ndcw3Am6ivrHvKpu9nbCeTZ+d5GQ9d2YjE3yHushpGbVZ5z1yy9dg4QBEN55Vo4OLTe5HsaYFW1QKIebHUCA3l0O7u/h8wdM3qtiNdb0I1RTsqvdARtZiUpY0843k1Mni4j2RIzrepEpZsv42/rcsomJ+8A/DoMss+AIv1eySyxD3uZuKVFpUEofCNOhU0ZR3B4MQlf6gtc290H4fOJpjYnEACI+ZM9XlLX2AououJbTSsDuJo1w7e/Pw6hNIp+7qEyS5zkGHrqVfP3LldMtPCf8EJymSUlIo1XeSjXAkJ8RHcHASP5u2N85mO0MibFPwB0zQwxReh1OYGM4aDF83LtKYJsDHjV8vv1EjpRcKOxfI0YBD9VaTjvY/ReYFKdTtN+hKh6pGF+1dRsWts9nId+r16ItiLCUE8k/97a2VCBpygDs7JhvuHperlD2dixnqw9YYZZ204hUVZPF+mImx3zEJXmkXsunmX174G1nEMQnAWHK+SVRX2MAE0PEJeuBlAPWVPZDmv08CV+e1qHvboFlEw5WrYqJcKfC1gyqyKipAer+6zH7Ke9iCsnqL9zRlpnXgIbXubgCLMOyLa5FXHb2RgkpE="
  file:
    - "scripts/linux/packages/appimage/apk-editor-studio_linux_dev.AppImage"
    - "scripts/linux/packages/deb/apk-editor-studio_linux_dev.deb"
    - "scripts/macos/packages/app/apk-editor-studio_macos_dev.app.zip"
    - "scripts/macos/packages/dmg/apk-editor-studio_macos_dev.dmg"
  name: Developer Build
  draft: false
  prerelease: true
  overwrite: true
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|[0-9]+\.[0-9]+\.[0-9]+)$
